version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.3-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
  rubocop:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.1.3-browsers
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: user_name
          POSTGRES_DB: your_db_name
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: run rubocop
          command: bundle exec rubocop
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.1.3-browsers
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: user_name
          POSTGRES_DB: your_db_name
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: user_name
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: webpacker compile
          command: bundle exec rake assets:precompile
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec
  deploy:
    docker:
      - image: cimg/ruby:3.1.3-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - add_ssh_keys:
          fingerprints:"8a:9b:fc:e3:12:a0:d3:1e:c2:62:98:a6:7b:56:d8:3d"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy
workflows:
  version: 2
  build_and_rubocop_and_test:
    jobs:
      - build
      - rubocop
      - test:
          requires:
            - build
            - rubocop
  deploy:
    jobs:
      - deploy:
          filters:
              branches:
                  only:
                  - main
